[allowlist]
    description = "Allowlisted files"
    files = [
        '''^test-values.yaml$''',
        '''^\.?gitleaks.toml$''',
        '''(.*?)(png|jpg|gif|doc|docx|pdf|bin|xls|pyc|zip)$''',
        '''(go.mod|go.sum)$'''
   ]
