apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: linkerd
    git:
      url: https://github.com/giantswarm/linkerd2-upstream
      ref: stable-2.13.x
    includePaths:
    - multicluster/charts/linkerd-multicluster/**/*
    - charts/partials/**/*
- path: helm/linkerd-multicluster/templates
  contents:
  - path: .
    directory:
      path: vendor/linkerd/multicluster/charts/linkerd-multicluster/templates
- path: helm/linkerd-multicluster/charts/partials
  contents:
  - path: .
    directory:
      path: vendor/linkerd/charts/partials
