version: 2.1
orbs:
  architect: giantswarm/architect@4.21.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          name: "package and push linkerd2-multicluster chart"
          context: architect
          executor: "app-build-suite"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "linkerd2-multicluster-target-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
