version: 2.1
orbs:
  architect: giantswarm/architect@0.13.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          name: "package and push linkerd2-multicluster-app chart"
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "linkerd2-multicluster-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
